[package]
name = "bin_dasm"
version = "0.1.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "4.1.3"
features = ["cargo"]
