[package]
name = "wqxtools"
version = "0.2.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2021"

[dependencies]
semver = "1.0.4"

[workspace]
members = [
  "bin_dasm",
  "gvb_interp",
  "gui-sciter",
  "config",
  "util"
]
