[env.debug]
PROFILE = 'debug'

[env.release]
PROFILE = 'release'

[tasks.all]
workspace = false
clear = true
dependencies = ["prepare-gui", "build-gui"]

[tasks.prepare-gui]
workspace = false
script_runner = "@shell"
script = """
cp gvb_interp/machines.yaml gui/machines.yaml
cp gvb_interp/config.yaml gui/config.yaml
cp -r gvb_interp/styles gui/styles
"""
dependencies = [
  { name = "header", path = "api_cpp_binding" }
]

[tasks.build-api]
workspace = false
dependencies = [
  { name = "build", path = "api_cpp_binding" }
]

[tasks.build-gui]
workspace = false
dependencies = [
  { name = "build-api" },
  { name = "build", path = "gui" }
]
