[tasks.release]
workspace = false
clear = true
dependencies = ["prepare-gui", "build-gui-release"]

[tasks.debug]
workspace = false
clear = true
dependencies = ["prepare-gui", "build-gui-debug"]

[tasks.prepare-gui]
workspace = false
script_runner = "@shell"
script = """
cp gvb_interp/machines.yaml gui/machines.yaml
cp gvb_interp/config.yaml gui/config.yaml
"""
dependencies = [
  { name = "header", path = "api_cpp_binding" }
]

[tasks.build-api]
workspace = false
dependencies = [
  { name = "build", path = "api_cpp_binding" }
]

[tasks.build-gui-debug]
workspace = false
dependencies = [
  { name = "build-api" },
  { name = "build", path = "gui" }
]

[tasks.build-gui-release]
workspace = false
dependencies = [
  { name = "build-api" },
  { name = "build", path = "gui" }
]