/* This file is auto-generated by cbindgen. Do not edit this file. */

#ifndef GVB_H
#define GVB_H

#include <cstdint>
using std::size_t;


namespace gvb {

struct Document;

struct CString {
  const char *data;
  size_t len;
};

template<typename E, typename T>
struct Either {
  enum class Tag {
    Left,
    Right,
  };

  struct Left_Body {
    E _0;
  };

  struct Right_Body {
    T _0;
  };

  Tag tag;
  union {
    Left_Body left;
    Right_Body right;
  };
};

struct CStr {
  const char *data;
  size_t len;
};

extern "C" {

Either<CString, Document*> load_document(const unsigned short *path,
                                         size_t len);

void destroy_document(Document *doc);

CStr document_text(Document *doc);

void destroy_string(CString str);

} // extern "C"

} // namespace gvb

#endif // GVB_H
