[package]
name = "gvb_interp"
version = "0.1.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.3.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = "0.7.3"
smallvec = "1.6.1"
