/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int sub_401000();
int (**sub_401010())();
void *__thiscall sub_401040(void *this, char a2);
_DWORD __thiscall CWinApp::~CWinApp(CWinApp *this); // idb
int __thiscall sub_4010B0(CWinApp *this); // idb
int __thiscall sub_401150(CDialog *this); // idb
int sub_4011E0();
CDialog *__thiscall sub_401210(CDialog *this);
void *__thiscall sub_401230(void *this, char a2);
int sub_401260();
int (**sub_401270())();
CDialog *__thiscall sub_401280(CDialog *this, struct CWnd *a2);
void *__thiscall sub_401330(void *this, char a2);
void __thiscall sub_401350(int this, struct CDataExchange *a2);
int (**sub_401380())();
int __thiscall sub_401390(CWnd *this); // idb
_DWORD *__stdcall sub_401F50(void *Memory);
signed int __thiscall sub_401F80(void *this, int a2);
char __stdcall sub_4024D0(const char *a1);
CString *__stdcall sub_402580(CString *a1, char a2);
int __thiscall sub_402690(CWnd *this);
BOOL __thiscall sub_402A90(HWND *this);
BOOL __thiscall sub_402AA0(HWND *this);
_DWORD __thiscall CDialog::~CDialog(CDialog *this); // idb
// void __cdecl operator delete(void *); idb
// _DWORD __thiscall CDialog::~CDialog(CDialog *this); idb
// _DWORD __thiscall CString::~CString(CString *this); idb
// int __thiscall CDialog::DoModal(CDialog *this); idb
// int __thiscall CWinApp::Enable3dControls(CWinApp *this); idb
// void __cdecl AfxEnableControlContainer(struct COccManager *); idb
// _DWORD __thiscall CString::CString(CString *this, const char *); idb
// int __thiscall CDialog::OnInitDialog(CDialog *this); idb
// _DWORD __thiscall CDialog::CDialog(CDialog *this, unsigned int, struct CWnd *); idb
// HINSTANCE __stdcall AfxFindResourceHandle(const char *, const char *); idb
// struct AFX_MODULE_STATE *__stdcall AfxGetModuleState(); idb
// int __thiscall CString::operator=(_DWORD, _DWORD); weak
// _DWORD __thiscall CString::CString(CString *this); idb
// void __stdcall DDX_Text(struct CDataExchange *, int, struct CString *); idb
// void __thiscall CWnd::CheckRadioButton(CWnd *this, int, int, int); idb
// int __thiscall CString::operator=(_DWORD, _DWORD); weak
// void CString::Format(CString *this, const char *, ...); idb
// int __thiscall CWnd::MessageBoxA(CWnd *this, const char *, const char *, unsigned int); idb
// int __thiscall CString::operator+=(_DWORD, _DWORD); weak
// int __thiscall CString::Mid(_DWORD, _DWORD, _DWORD); weak
// int __thiscall CString::Mid(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __thiscall CString::operator+=(_DWORD, _DWORD); weak
// _DWORD __thiscall CString::CString(CString *this, const struct CString *); idb
// int __thiscall CString::Find(CString *this, char, int); idb
// void __thiscall CFile::Write(CFile *this, const void *, unsigned int); idb
// unsigned int __thiscall CFile::Read(CFile *this, void *, unsigned int); idb
// _DWORD __thiscall CFile::~CFile(CFile *this); idb
// void __thiscall CFile::Close(CFile *this); idb
// unsigned int __thiscall CFile::GetLength(CFile *this); idb
// _DWORD __thiscall CFile::CFile(CFile *this, const char *, unsigned int); idb
// int _CxxFrameHandler(void); weak
int sub_402F12();
int SEH_401150();
int SEH_401280();
// int __usercall sub_403000@<eax>(int a1@<ebp>);
// int __usercall sub_403020@<eax>(int a1@<ebp>);
// int __usercall sub_40302B@<eax>(int a1@<ebp>);
// int __usercall sub_403036@<eax>(int a1@<ebp>);
// int __usercall sub_403041@<eax>(int a1@<ebp>);
// int __usercall sub_403060@<eax>(int a1@<ebp>);
int sub_403068();
// int __usercall sub_403080@<eax>(int a1@<ebp>);
// int __usercall sub_40308B@<eax>(int a1@<ebp>);
// int __usercall sub_403096@<eax>(int a1@<ebp>);
// int __usercall sub_4030A1@<eax>(int a1@<ebp>);
// int __usercall sub_4030C0@<eax>(int a1@<ebp>);
// int __usercall sub_4030CB@<eax>(int a1@<ebp>);
// int __usercall sub_4030D6@<eax>(int a1@<ebp>);
int SEH_401F80();
int SEH_402580();
int SEH_402690();
// int __cdecl fclose(FILE *File);
// FILE *__cdecl fopen(const char *Filename, const char *Mode);
// void __cdecl free(void *Memory);
// int __cdecl fputc(int Ch, FILE *File);
// size_t __cdecl fwrite(const void *Str, size_t Size, size_t Count, FILE *File);
// LRESULT __stdcall SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// BOOL __stdcall EnableWindow(HWND hWnd, BOOL bEnable);
// HICON __stdcall LoadIconA(HINSTANCE hInstance, LPCSTR lpIconName);

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN CWinApp::messageMap; weak
// extern _UNKNOWN CDialog::messageMap; weak
int (*off_404260)() = &sub_401000; // weak
int (*off_404340)() = &sub_401260; // weak
int (*off_404360)() = &sub_401260; // weak
struct CRuntimeClass *(__thiscall *off_404488)(CDialog *this) = &CDialog::GetRuntimeClass; // weak
struct CRuntimeClass *(__thiscall *off_404560)(CDialog *this) = &CDialog::GetRuntimeClass; // weak
int dword_404E20[111] =
{
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
}; // idb
int dword_404FDC[] = { 0 }; // weak
char *off_405020[111] =
{
  "END",
  "FOR",
  "NEXT",
  "DATA",
  "INPUT",
  "DEL",
  "DIM",
  "READ",
  "SWAP",
  "TRACE",
  "NOTRACE",
  "POP",
  "LET",
  "GOTO",
  "RUN",
  "IF",
  "RESTORE",
  "GOSUB",
  "RETURN",
  "REM",
  "STOP",
  "ON",
  "DEF",
  "POKE",
  "PRINT",
  "CONT",
  "LIST",
  "CLEAR",
  "NEW",
  "TEXT",
  "GRAPH",
  "SYSTEM",
  "NORMAL",
  "INVERSE",
  "FLASH",
  "PLAY",
  "BEEP",
  "INKEY$",
  "LOAD",
  "SAVE",
  "KILL",
  "FILES",
  "OPEN",
  "CLOSE",
  "WRITE",
  "FIELD",
  "GET",
  "PUT",
  "LSET",
  "RSET",
  "AUTO",
  "LOCATE",
  "DRAW",
  "LINE",
  "BOX",
  "CIRCLE",
  "ELLIPSE",
  "CLS",
  "EDIT",
  "WHILE",
  "WEND",
  "CALL",
  "RENAME",
  "COPY",
  "TAB",
  "TO",
  "FN",
  "SPC",
  "THEN",
  "ELSE",
  "AT",
  "NOT",
  "STEP",
  "+",
  "-",
  "*",
  "/",
  "^",
  "AND",
  "OR",
  ">",
  "=",
  "<",
  "SGN",
  "INT",
  "ABS",
  "POS",
  "SQR",
  "RND",
  "LOG",
  "EXP",
  "COS",
  "SIN",
  "TAN",
  "ATN",
  "PEEK",
  "LEN",
  "STR$",
  "VAL",
  "ASC",
  "MKS$",
  "MKI$",
  "CVS$",
  "CVI$",
  "LOF",
  "EOF",
  "CHR$",
  "LEFT$",
  "RIGHT$",
  "MID$",
  "END_TOK"
}; // weak
char aEndTok[8] = "END_TOK"; // weak
char asc_40564C[] = "+-*/^>=< :;,\"()"; // idb
char byte_4056D0 = '×'; // idb
char Mode[3] = "wb"; // idb
char aIae[3] = "ÌáÊ"; // idb
char asc_4057CC[2] = "\""; // weak
char aC[] = "%c"; // idb
char aS[] = "%s"; // idb
char aCC[] = "%c%c"; // idb
char asc_4057E0[2] = " "; // weak
char aD[] = "%d"; // idb
_UNKNOWN unk_4058BC; // weak
char byte_4058C0 = '\0'; // idb


//----- (00401000) --------------------------------------------------------
int sub_401000()
{
  return CWinApp::messageMap;
}

//----- (00401010) --------------------------------------------------------
int (**sub_401010())()
{
  return &off_404260;
}
// 404260: using guessed type int (*off_404260)();

//----- (00401040) --------------------------------------------------------
void *__thiscall sub_401040(void *this, char a2)
{
  void *v2; // esi

  v2 = this;
  CWinApp::~CWinApp((CWinApp *)this);
  if ( a2 & 1 )
    operator delete(v2);
  return v2;
}

//----- (004010B0) --------------------------------------------------------
int __thiscall sub_4010B0(CWinApp *this)
{
  CWinApp *v1; // esi
  char v3; // [esp+4h] [ebp-7Ch]
  char v4; // [esp+68h] [ebp-18h]
  char v5; // [esp+6Ch] [ebp-14h]
  int v6; // [esp+7Ch] [ebp-4h]

  v1 = this;
  AfxEnableControlContainer(0);
  CWinApp::Enable3dControls(v1);
  sub_401280((CDialog *)&v3, 0);
  v6 = 0;
  *((_DWORD *)v1 + 8) = &v3;
  CDialog::DoModal((CDialog *)&v3);
  v6 = 2;
  CString::~CString((CString *)&v5);
  LOBYTE(v6) = 1;
  CString::~CString((CString *)&v4);
  v6 = -1;
  CDialog::~CDialog((CDialog *)&v3);
  return 0;
}

//----- (00401150) --------------------------------------------------------
int __thiscall sub_401150(CDialog *this)
{
  CDialog *v1; // esi

  v1 = this;
  CString::~CString((CDialog *)((char *)this + 104));
  CString::~CString((CDialog *)((char *)v1 + 100));
  return CDialog::~CDialog(v1);
}

//----- (004011E0) --------------------------------------------------------
int sub_4011E0()
{
  return CString::CString((CString *)&unk_4058BC, asc_40564C);
}

//----- (00401210) --------------------------------------------------------
CDialog *__thiscall sub_401210(CDialog *this)
{
  CDialog *v1; // esi

  v1 = this;
  CDialog::CDialog(this, 0x64u, 0);
  *(_DWORD *)v1 = &off_404488;
  return v1;
}
// 404488: using guessed type struct CRuntimeClass *(__thiscall *off_404488)(CDialog *this);

//----- (00401230) --------------------------------------------------------
void *__thiscall sub_401230(void *this, char a2)
{
  void *v2; // esi

  v2 = this;
  CDialog::~CDialog((CDialog *)this);
  if ( a2 & 1 )
    operator delete(v2);
  return v2;
}

//----- (00401260) --------------------------------------------------------
int sub_401260()
{
  return CDialog::messageMap;
}

//----- (00401270) --------------------------------------------------------
int (**sub_401270())()
{
  return &off_404340;
}
// 404340: using guessed type int (*off_404340)();

//----- (00401280) --------------------------------------------------------
CDialog *__thiscall sub_401280(CDialog *this, struct CWnd *a2)
{
  CDialog *v2; // esi
  HINSTANCE v3; // eax

  v2 = this;
  CDialog::CDialog(this, 0x66u, a2);
  CString::CString((CDialog *)((char *)v2 + 100));
  CString::CString((CDialog *)((char *)v2 + 104));
  *(_DWORD *)v2 = &off_404560;
  CString::operator=((char *)v2 + 100, &byte_4058C0);
  CString::operator=((char *)v2 + 104, &byte_4058C0);
  AfxGetModuleState();
  v3 = AfxFindResourceHandle((const char *)0x80, (const char *)0xE);
  *((_DWORD *)v2 + 27) = LoadIconA(v3, (LPCSTR)0x80);
  return v2;
}
// 402C9A: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 404560: using guessed type struct CRuntimeClass *(__thiscall *off_404560)(CDialog *this);

//----- (00401330) --------------------------------------------------------
void *__thiscall sub_401330(void *this, char a2)
{
  void *v2; // esi

  v2 = this;
  sub_401150((CDialog *)this);
  if ( a2 & 1 )
    operator delete(v2);
  return v2;
}

//----- (00401350) --------------------------------------------------------
void __thiscall sub_401350(int this, struct CDataExchange *a2)
{
  int v2; // esi

  v2 = this;
  DDX_Text(a2, 1002, (struct CString *)(this + 100));
  DDX_Text(a2, 1003, (struct CString *)(v2 + 104));
}

//----- (00401380) --------------------------------------------------------
int (**sub_401380())()
{
  return &off_404360;
}
// 404360: using guessed type int (*off_404360)();

//----- (00401390) --------------------------------------------------------
int __thiscall sub_401390(CWnd *this)
{
  CWnd *v1; // esi

  v1 = this;
  CDialog::OnInitDialog(this);
  SendMessageA(*((HWND *)v1 + 8), 0x80u, 1u, *((_DWORD *)v1 + 27));
  SendMessageA(*((HWND *)v1 + 8), 0x80u, 0, *((_DWORD *)v1 + 27));
  *((_DWORD *)v1 + 24) = 1;
  CWnd::CheckRadioButton(v1, 1000, 1001, 1000);
  return 1;
}

//----- (00401F50) --------------------------------------------------------
_DWORD *__stdcall sub_401F50(void *Memory)
{
  _DWORD *result; // eax
  _DWORD *v2; // esi

  result = Memory;
  if ( Memory )
  {
    do
    {
      v2 = (_DWORD *)result[26];
      free(result);
      result = v2;
    }
    while ( v2 );
  }
  return result;
}

//----- (00401F80) --------------------------------------------------------
signed int __thiscall sub_401F80(void *this, int a2)
{
  void *v2; // ebp
  const char *v3; // ST20_4
  FILE *v4; // esi
  int v5; // ebx
  const char *v6; // ecx
  int v7; // eax
  int v8; // edi
  int v9; // esi
  char *v10; // eax
  const char *v11; // ecx
  CString *v12; // eax
  int v13; // eax
  const char *v14; // ecx
  char *v15; // eax
  const char *v16; // ecx
  CString *v17; // eax
  int v18; // eax
  int v19; // ecx
  unsigned __int8 v20; // al
  int v21; // eax
  int v22; // eax
  FILE *v23; // esi
  int v24; // edi
  char *v26; // [esp-4h] [ebp-58h]
  char v27; // [esp+10h] [ebp-44h]
  int v28; // [esp+14h] [ebp-40h]
  void *v29; // [esp+18h] [ebp-3Ch]
  int v30; // [esp+1Ch] [ebp-38h]
  FILE *File; // [esp+20h] [ebp-34h]
  char v32[4]; // [esp+24h] [ebp-30h]
  char v33; // [esp+28h] [ebp-2Ch]
  char v34; // [esp+2Ch] [ebp-28h]
  char v35; // [esp+30h] [ebp-24h]
  char v36; // [esp+34h] [ebp-20h]
  char v37; // [esp+38h] [ebp-1Ch]
  const char **v38; // [esp+3Ch] [ebp-18h]
  char Str; // [esp+40h] [ebp-14h]
  int v40; // [esp+41h] [ebp-13h]
  int v41; // [esp+50h] [ebp-4h]
  signed int v42; // [esp+58h] [ebp+4h]

  v2 = this;
  v30 = 6592;
  CString::CString((CString *)&v28);
  v41 = 0;
  CString::CString((CString *)&v29, &byte_4058C0);
  LOBYTE(v41) = 1;
  CString::CString((CString *)&v27);
  v26 = "wb";
  Str = byte_4058C0;
  v3 = (const char *)*((_DWORD *)v2 + 26);
  LOBYTE(v41) = 2;
  v40 = 0;
  v4 = fopen(v3, Mode);
  File = v4;
  v5 = a2;
  if ( a2 )
  {
    while ( 1 )
    {
      CString::operator=(&v28, v5 + 9);
      CString::operator=(&v29, &byte_4058C0);
      v7 = v28;
      v42 = 0;
      do
      {
        v8 = *(_DWORD *)(v7 - 8);
        v9 = 0;
        if ( v8 <= 0 )
          goto LABEL_10;
        while ( 1 )
        {
          v32[0] = *(_BYTE *)(v9 + v7);
          if ( CString::Find((CString *)&unk_4058BC, v32[0], 0) != -1 )
            break;
          if ( ++v9 >= v8 )
            goto LABEL_10;
          v7 = v28;
        }
        if ( v9 >= v8 )
        {
LABEL_10:
          v26 = (char *)v6;
          v38 = (const char **)&v26;
          CString::CString((CString *)&v26, (const struct CString *)&v28);
          v10 = (char *)sub_4024D0(v26);
          if ( (_BYTE)v10 )
          {
            v26 = v10;
            CString::Format((CString *)&v27, aC, v10);
            CString::operator+=(&v29, &v27);
          }
          else
          {
            v26 = (char *)v11;
            v38 = (const char **)&v26;
            CString::CString((CString *)&v26, (const struct CString *)&v28);
            v12 = sub_402580((CString *)&v33, (char)v26);
            LOBYTE(v41) = 3;
            CString::operator+=(&v29, v12);
            LOBYTE(v41) = 2;
            CString::~CString((CString *)&v33);
          }
LABEL_13:
          CString::operator=(&v28, &byte_4058C0);
          goto LABEL_33;
        }
        if ( v9 )
        {
          v13 = CString::Mid(&v28, &v34, 0, v9);
          LOBYTE(v41) = 4;
          CString::operator=(&v27, v13);
          LOBYTE(v41) = 2;
          CString::~CString((CString *)&v34);
          v26 = (char *)v14;
          v38 = (const char **)&v26;
          CString::CString((CString *)&v26, (const struct CString *)&v27);
          v15 = (char *)sub_4024D0(v26);
          if ( (_BYTE)v15 )
          {
            v26 = v15;
            CString::Format((CString *)&v27, aC, v15);
            CString::operator+=(&v29, &v27);
            v42 = 1;
          }
          else
          {
            v26 = (char *)v16;
            v38 = (const char **)&v26;
            CString::CString((CString *)&v26, (const struct CString *)&v27);
            v17 = sub_402580((CString *)&v35, (char)v26);
            LOBYTE(v41) = 5;
            CString::operator+=(&v29, v17);
            LOBYTE(v41) = 2;
            CString::~CString((CString *)&v35);
          }
        }
        v18 = *(char *)(v9 + v28);
        switch ( v18 )
        {
          case 32:
            if ( !v42 )
            {
              v26 = (char *)*(char *)(v9 + v28);
              CString::Format((CString *)&v27, aC, v18);
              CString::operator+=(&v29, &v27);
            }
            break;
          case 34:
            CString::operator+=(&v29, asc_4057CC);
            ++v9;
            do
            {
              v19 = v28;
              v20 = *(_BYTE *)(v9 + v28);
              if ( v20 == 34 )
                break;
              if ( v20 >= 0x80u )
              {
                v26 = (char *)31;
                CString::Format((CString *)&v27, aC, 31);
                CString::operator+=(&v29, &v27);
                v21 = CString::Mid(&v28, &v36, v9, 2);
                LOBYTE(v41) = 6;
                CString::operator+=(&v29, v21);
                LOBYTE(v41) = 2;
                CString::~CString((CString *)&v36);
                ++v9;
              }
              else
              {
                v26 = (char *)(char)v20;
                CString::Format((CString *)&v27, aC, (char)v20);
                CString::operator+=(&v29, &v27);
              }
              v19 = v28;
              ++v9;
            }
            while ( v9 < *(_DWORD *)(v28 - 8) );
            if ( v9 < *(_DWORD *)(v19 - 8) )
              CString::operator+=(&v29, asc_4057CC);
            break;
          case 40:
          case 41:
          case 44:
          case 58:
          case 59:
            v26 = (char *)*(char *)(v9 + v28);
            CString::Format((CString *)&v27, aC, v26);
            CString::operator+=(&v29, &v27);
            break;
          case 42:
          case 43:
          case 45:
          case 47:
          case 60:
          case 61:
          case 62:
          case 94:
            v26 = (char *)*(char *)(v9 + v28);
            CString::Format((CString *)&v27, aC);
            v38 = (const char **)&v26;
            CString::CString((CString *)&v26, (const struct CString *)&v27);
            v26 = (char *)sub_4024D0(v26);
            CString::Format((CString *)&v27, aC, v26);
            CString::operator+=(&v29, &v27);
            break;
          default:
            break;
        }
        if ( v9 >= *(_DWORD *)(v28 - 8) )
          goto LABEL_13;
        v22 = CString::Mid(&v28, &v37, v9 + 1);
        LOBYTE(v41) = 7;
        CString::operator=(&v28, v22);
        LOBYTE(v41) = 2;
        CString::~CString((CString *)&v37);
LABEL_33:
        v7 = v28;
        v6 = *(const char **)(v28 - 8);
      }
      while ( (signed int)v6 > 0 );
      v23 = File;
      v30 += *((_DWORD *)v29 - 2) + 1;
      v24 = v30;
      fputc(0, File);
      Str = v24 + 1;
      LOBYTE(v40) = (v24 + 1) / 256;
      BYTE1(v40) = *(_BYTE *)v5;
      HIWORD(v40) = (unsigned __int8)(*(_WORD *)v5 >> 8);
      fwrite(&Str, 4u, 1u, v23);
      fwrite(v29, *((_DWORD *)v29 - 2), 1u, v23);
      v5 = *(_DWORD *)(v5 + 104);
      if ( !v5 )
      {
        v4 = File;
        break;
      }
    }
  }
  fputc(0, v4);
  fputc(0, v4);
  fputc(0, v4);
  fclose(v4);
  LOBYTE(v41) = 1;
  CString::~CString((CString *)&v27);
  LOBYTE(v41) = 0;
  CString::~CString((CString *)&v29);
  v41 = -1;
  CString::~CString((CString *)&v28);
  return 1;
}
// 402C9A: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 402CCA: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);
// 402CF4: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);
// 402D06: using guessed type int __thiscall CString::Mid(_DWORD, _DWORD, _DWORD);
// 402D0C: using guessed type int __thiscall CString::Mid(_DWORD, _DWORD, _DWORD, _DWORD);
// 402D12: using guessed type int __thiscall CString::operator+=(_DWORD, _DWORD);

//----- (004024D0) --------------------------------------------------------
char __stdcall sub_4024D0(const char *a1)
{
  const char **v1; // ebp
  char v2; // bl
  char v4; // [esp+10h] [ebp-4h]

  v4 = -128;
  v1 = (const char **)off_405020;
  while ( strcmp(a1, *v1) )
  {
    if ( !strcmp(*v1, aEndTok) )
    {
      v2 = 0;
      goto LABEL_7;
    }
    ++v1;
    ++v4;
  }
  v2 = v4;
LABEL_7:
  CString::~CString((CString *)&a1);
  return v2;
}
// 405020: using guessed type char *off_405020[111];

//----- (00402580) --------------------------------------------------------
CString *__stdcall sub_402580(CString *a1, char a2)
{
  int v2; // esi
  int v3; // ecx
  int v4; // edi
  char *v5; // eax
  char v6; // dl
  char *v7; // eax
  int v9; // [esp+8h] [ebp-414h]
  int v10; // [esp+Ch] [ebp-410h]
  char v11; // [esp+10h] [ebp-40Ch]
  char v12; // [esp+11h] [ebp-40Bh]
  __int16 v13; // [esp+40Dh] [ebp-Fh]
  char v14; // [esp+40Fh] [ebp-Dh]
  int v15; // [esp+418h] [ebp-4h]

  v10 = 0;
  v11 = byte_4058C0;
  v15 = 1;
  memset(&v12, 0, 0x3FCu);
  v13 = 0;
  v14 = 0;
  CString::CString((CString *)&v9);
  LOBYTE(v15) = 2;
  CString::operator=(&v9, &a2);
  v2 = v9;
  v3 = 0;
  v4 = *(_DWORD *)(v9 - 8);
  if ( v4 > 0 )
  {
    v5 = &v11;
    do
    {
      v6 = *(_BYTE *)(v3 + v2);
      if ( (unsigned __int8)v6 >= 0x80u )
      {
        *v5 = 31;
        v7 = v5 + 1;
        *v7 = v6;
        v6 = *(_BYTE *)(v3 + v2 + 1);
        v5 = v7 + 1;
        ++v3;
      }
      *v5++ = v6;
      ++v3;
    }
    while ( v3 < v4 );
  }
  CString::Format((CString *)&v9, aS, &v11);
  CString::CString(a1, (const struct CString *)&v9);
  v10 = 1;
  LOBYTE(v15) = 1;
  CString::~CString((CString *)&v9);
  LOBYTE(v15) = 0;
  CString::~CString((CString *)&a2);
  return a1;
}
// 402CCA: using guessed type int __thiscall CString::operator=(_DWORD, _DWORD);

//----- (00402690) --------------------------------------------------------
int __thiscall sub_402690(CWnd *this)
{
  CWnd *v1; // esi
  const char *v2; // eax
  const char *v3; // eax
  signed int v4; // edi
  signed int v5; // ebx
  int result; // eax
  signed int v7; // ebp
  signed int i; // esi
  int v9; // eax
  void *v10; // [esp+Ch] [ebp-9Ch]
  void *v11; // [esp+10h] [ebp-98h]
  char v12; // [esp+14h] [ebp-94h]
  char v13; // [esp+24h] [ebp-84h]
  CWnd *v14; // [esp+34h] [ebp-74h]
  unsigned __int8 v15; // [esp+38h] [ebp-70h]
  unsigned __int8 v16; // [esp+3Ah] [ebp-6Eh]
  unsigned __int8 v17; // [esp+3Bh] [ebp-6Dh]
  int v18; // [esp+A4h] [ebp-4h]

  v1 = this;
  v2 = (const char *)*((_DWORD *)this + 25);
  v14 = this;
  CFile::CFile((CFile *)&v13, v2, 0x8000u);
  v3 = (const char *)*((_DWORD *)v1 + 26);
  v4 = 0;
  v18 = 0;
  CFile::CFile((CFile *)&v12, v3, 0x8001u);
  LOBYTE(v18) = 1;
  CString::CString((CString *)&v11);
  LOBYTE(v18) = 2;
  CString::CString((CString *)&v10);
  LOBYTE(v18) = 3;
  v5 = CFile::GetLength((CFile *)&v13);
  if ( v5 )
  {
    CFile::Read((CFile *)&v13, &v15, 1u);
    if ( v5 > 0 )
    {
      do
      {
        if ( CFile::Read((CFile *)&v13, &v15, 4u) != 4 )
          break;
        v4 += 4;
        CString::Format((CString *)&v11, aD, v16 + (v17 << 8));
        CFile::Write((CFile *)&v12, v11, *((_DWORD *)v11 - 2));
        CFile::Write((CFile *)&v12, asc_4057E0, 1u);
        v7 = 32;
        while ( 1 )
        {
          CFile::Read((CFile *)&v13, &v15, 1u);
          ++v4;
          i = v15;
          if ( v15 )
          {
            if ( v15 == 31 )
            {
              CFile::Read((CFile *)&v13, &v15, 2u);
              CFile::Write((CFile *)&v12, &v15, 2u);
              v4 += 2;
            }
            else if ( v15 == 34 )
            {
              CFile::Write((CFile *)&v12, &v15, 1u);
              if ( v4 < v5 )
              {
                CFile::Read((CFile *)&v13, &v15, 1u);
                ++v4;
                for ( i = v15; v15; i = v15 )
                {
                  if ( i == 31 )
                  {
                    CFile::Read((CFile *)&v13, &v15, 2u);
                    CFile::Write((CFile *)&v12, &v15, 2u);
                    v4 += 2;
                  }
                  else
                  {
                    CFile::Write((CFile *)&v12, &v15, 1u);
                    if ( i == 34 )
                      break;
                  }
                  if ( v4 >= v5 )
                    break;
                  CFile::Read((CFile *)&v13, &v15, 1u);
                  ++v4;
                }
              }
            }
            else if ( v15 >= 0x80u )
            {
              if ( dword_404FDC[v15] == 2 && v7 != 32 )
                CFile::Write((CFile *)&v12, asc_4057E0, 1u);
              CString::Format((CString *)&v10, aS, dword_404E20[i]);
              CFile::Write((CFile *)&v12, v10, *((_DWORD *)v10 - 2));
              v9 = dword_404FDC[i];
              if ( v9 == 1 || v9 == 2 )
                CFile::Write((CFile *)&v12, asc_4057E0, 1u);
            }
            else
            {
              CFile::Write((CFile *)&v12, &v15, 1u);
            }
          }
          v7 = i;
          if ( !i )
            break;
          if ( v4 >= v5 )
            goto LABEL_30;
        }
        CString::Format((CString *)&v10, aCC, 13, 10);
        CFile::Write((CFile *)&v12, v10, *((_DWORD *)v10 - 2));
      }
      while ( v4 < v5 );
    }
LABEL_30:
    CFile::Close((CFile *)&v13);
    CFile::Close((CFile *)&v12);
    CWnd::MessageBoxA(v14, &byte_4056D0, aIae, 0);
    LOBYTE(v18) = 2;
    CString::~CString((CString *)&v10);
    LOBYTE(v18) = 1;
    CString::~CString((CString *)&v11);
    LOBYTE(v18) = 0;
    CFile::~CFile((CFile *)&v12);
    v18 = -1;
    result = CFile::~CFile((CFile *)&v13);
  }
  else
  {
    CFile::Close((CFile *)&v13);
    CFile::Close((CFile *)&v12);
    LOBYTE(v18) = 2;
    CString::~CString((CString *)&v10);
    LOBYTE(v18) = 1;
    CString::~CString((CString *)&v11);
    LOBYTE(v18) = 0;
    CFile::~CFile((CFile *)&v12);
    v18 = -1;
    result = CFile::~CFile((CFile *)&v13);
  }
  return result;
}
// 404FDC: using guessed type int dword_404FDC[];

//----- (00402A90) --------------------------------------------------------
BOOL __thiscall sub_402A90(HWND *this)
{
  return EnableWindow(this[8], 0);
}

//----- (00402AA0) --------------------------------------------------------
BOOL __thiscall sub_402AA0(HWND *this)
{
  return EnableWindow(this[8], 1);
}

//----- (00402F12) --------------------------------------------------------
int sub_402F12()
{
  return 0;
}

//----- (00402FC3) --------------------------------------------------------
int SEH_401150()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

//----- (00402FEE) --------------------------------------------------------
int SEH_401280()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

//----- (00403000) --------------------------------------------------------
int __usercall sub_403000@<eax>(int a1@<ebp>)
{
  return CDialog::~CDialog((CDialog *)(a1 - 108));
}

//----- (00403020) --------------------------------------------------------
int __usercall sub_403020@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 528));
}

//----- (0040302B) --------------------------------------------------------
int __usercall sub_40302B@<eax>(int a1@<ebp>)
{
  CString::~CString((CString *)(a1 - 520 + 176));
  return CDialog::~CDialog((CDialog *)(a1 - 520));
}

//----- (00403036) --------------------------------------------------------
int __usercall sub_403036@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 524));
}

//----- (00403041) --------------------------------------------------------
int __usercall sub_403041@<eax>(int a1@<ebp>)
{
  return CDialog::~CDialog((CDialog *)(a1 - 520));
}

//----- (00403060) --------------------------------------------------------
int __usercall sub_403060@<eax>(int a1@<ebp>)
{
  return CDialog::~CDialog(*(CDialog **)(a1 - 16));
}

//----- (00403068) --------------------------------------------------------
int sub_403068()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

//----- (00403080) --------------------------------------------------------
int __usercall sub_403080@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 528));
}

//----- (0040308B) --------------------------------------------------------
int __usercall sub_40308B@<eax>(int a1@<ebp>)
{
  int retaddr; // [esp+0h] [ebp+0h]

  retaddr = a1 - 520;
  CString::~CString((CString *)(a1 - 520 + 176));
  return CDialog::~CDialog((CDialog *)(a1 - 520));
}

//----- (00403096) --------------------------------------------------------
int __usercall sub_403096@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 524));
}

//----- (004030A1) --------------------------------------------------------
int __usercall sub_4030A1@<eax>(int a1@<ebp>)
{
  return CDialog::~CDialog((CDialog *)(a1 - 520));
}

//----- (004030C0) --------------------------------------------------------
int __usercall sub_4030C0@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 308));
}

//----- (004030CB) --------------------------------------------------------
int __usercall sub_4030CB@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 304));
}

//----- (004030D6) --------------------------------------------------------
int __usercall sub_4030D6@<eax>(int a1@<ebp>)
{
  return CString::~CString((CString *)(a1 - 272));
}

//----- (00403140) --------------------------------------------------------
int SEH_401F80()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

//----- (0040317D) --------------------------------------------------------
int SEH_402580()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

//----- (004031BC) --------------------------------------------------------
int SEH_402690()
{
  return _CxxFrameHandler();
}
// 402D86: using guessed type int _CxxFrameHandler(void);

// ALL OK, 42 function(s) have been successfully decompiled
